### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '!'.

### ISSUE THREAD

**Issue by LZH-0225** [Markfryazino/wav2lip-hq#25]
```
Using cuda for inference.
(80, 2612)
Length of mel chunks: 813
  0%|                                                                                             | 0/7 [00:00<?, ?it/s]Reading video frames from start...
  0%|                                                                                             | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 355, in <module>
    main()
  File "inference.py", line 292, in main
    for i, (img_batch, mel_batch, frames, coords) in enumerate(tqdm(gen,
  File "/home/lizhaohui/miniconda3/envs/wav2lip/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "inference.py", line 156, in datagen
    face, coords = face_detect([frame_to_save])[0]
  File "inference.py", line 93, in face_detect
    detector = face_detection.FaceAlignment(face_detection.LandmarksType._2D,
  File "/home/lizhaohui/wav2lip-hq/face_detection/api.py", line 62, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "/home/lizhaohui/wav2lip-hq/face_detection/detection/sfd/sfd_detector.py", line 24, in __init__
    model_weights = torch.load(path_to_detector)
  File "/home/lizhaohui/miniconda3/envs/wav2lip/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/lizhaohui/miniconda3/envs/wav2lip/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '!'.
```
The above error occurred in my operation

**Comment by wsx958191** [comment]
hello, I have also encountered this problem. How can I solve this problem ?

**Comment by LZH-0225** [comment]
> hello, I have also encountered this problem. How can I solve this problem ?

I didn't solve it.
The paddeGAN wav2lip I use now.
https://github.com/PaddlePaddle/PaddleGAN

**Comment by wsx958191** [comment]
Thank you very much for your reply. It seems that padlegan is not effective. Can you add wechat for communication? wsx958191331
