### ISSUE TITLE
net_d_67500 and net_g_67500 models are missing

### ISSUE THREAD

**Issue by devvikas** [Markfryazino/wav2lip-hq#3]
Are these models available here:

https://drive.google.com/drive/folders/15DgDtfaLASQ3iAPJEVHQF49g9msexECG

I tried to use the ESRGAN models and getting following error:

```
2021-07-17 21:21:57,934 INFO: Loading VGGStyleDiscriminator128 model from /media/vikas/972ed3bd-d92e-4181-a3db-34137c27f780/vikas/work/john/wav2lip-hq-main/experiments/001_ESRGAN_x4_f64b23_custom16k_500k_B16G1_wandb/models/net_d_67500.pth.
2021-07-17 21:21:57,988 WARNING: Current net - loaded net:
2021-07-17 21:21:57,988 WARNING:   bn0_1.bias
2021-07-17 21:21:57,988 WARNING:   bn0_1.num_batches_tracked
2021-07-17 21:21:57,988 WARNING:   bn0_1.running_mean
2021-07-17 21:21:57,988 WARNING:   bn0_1.running_var
..
..
..
2021-07-17 21:21:58,014 WARNING:   conv_hr.weight
2021-07-17 21:21:58,014 WARNING:   conv_last.bias
2021-07-17 21:21:58,014 WARNING:   conv_last.weight
2021-07-17 21:21:58,014 WARNING:   conv_up1.bias
2021-07-17 21:21:58,014 WARNING:   conv_up1.weight
2021-07-17 21:21:58,014 WARNING:   conv_up2.bias
2021-07-17 21:21:58,014 WARNING:   conv_up2.weight
Traceback (most recent call last):
  File "basicsr/train.py", line 221, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 138, in train_pipeline
    model = build_model(opt)
  File "/media/vikas/972ed3bd-d92e-4181-a3db-34137c27f780/vikas/work/john/wav2lip-hq-main/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/media/vikas/972ed3bd-d92e-4181-a3db-34137c27f780/vikas/work/john/wav2lip-hq-main/basicsr/models/sr_model.py", line 32, in __init__
    self.init_training_settings()
  File "/media/vikas/972ed3bd-d92e-4181-a3db-34137c27f780/vikas/work/john/wav2lip-hq-main/basicsr/models/srgan_model.py", line 42, in init_training_settings
    self.load_network(self.net_d, load_path, self.opt['path'].get('strict_load_d', True))
  File "/media/vikas/972ed3bd-d92e-4181-a3db-34137c27f780/vikas/work/john/wav2lip-hq-main/basicsr/models/base_model.py", line 261, in load_network
    net.load_state_dict(load_net, strict=strict)
  File "/home/vikas/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
```

**Comment by waleedrazakhan92** [comment]
Hi, any luck with the generator and discriminator weights?

**Comment by freecui** [comment]
I have the same problem. @devvikas  Do you find these two models?

**Comment by davidvfx07** [comment]
This is a big issue. I can't move forward without these files.

**Comment by davidvfx07** [comment]
I found a solution!
The problem is that the author is using a pretrained state which wants to access the already trained model. The only issue is that they didn't provide to model to keep training off of.

Solution:
Remove line `resume_state: checkpoints/pretrained.state` from `train_basicsr.yml`

Hope this helps!

**Comment by nirvitarka** [comment]
I removed the line 
resume_state: checkpoints/pretrained.state from train_basicsr.yml

The for the error about 128 x 128 dimensions. So I resized "hq" images to 128x128 and "lq" images to 32x32.

Now I am getting error 
 LQ (32, 32) is smaller than patch size (96, 96)
in 
/basicsr/data/transforms.py", line 59, in paired_random_crop

Where exactly need to set this patch size?
Has anyone got the training working without the pretrained state?
